FROM node:24.4.0

RUN useradd --user-group --create-home --shell /bin/false app
ENV HOME=/home/app
WORKDIR $HOME/src

COPY package.json package-lock.json eslint.config.js ./
RUN npm ci
COPY ./src ./src
COPY ./test ./test

CMD ["npm", "test"]
